% Test with four vortex.

function demo_vortex()
tspan = [0,4];
y0 = [1,2,3,4,5,6,7,8];
gamma = [1,2,3,4];
m = {'euler','eulerb','eulert','midpoint','eulers','verlet','gauss'};
printf('Demo: Four-Vortex Problem\n');
for i = 1:length(m)
  printf('solver: %s\n',m{i});
  switch m{i}
    case {'euler','eulerb'}
      N = 1e3;
    otherwise
      N = 1e2;
  end
  t{i} = linspace(tspan(1),tspan(2),N);
  y{i} = feval(m{i},@(y) ode_vortex(y,gamma),t{i},y0);
  [unused,H{i},L{i},P{i},Q{i}] = ode_vortex(y{i},gamma);
end
[unused,He,Le,Pe,Qe] = ode_vortex(y0,gamma);
figure;
semilogy(t{1},abs(H{1}-He)+eps, '-;Euler;', ...
         t{2},abs(H{2}-He)+eps, '-;Backward Euler;', ...
         t{3},abs(H{3}-He)+eps, '-;Trapesoidal rule;', ...
         t{4},abs(H{4}-He)+eps, '-;Implicit midpoint rule;', ...
         t{5},abs(H{5}-He)+eps, '-;Symplectic Euler;', ...
         t{6},abs(H{6}-He)+eps, '-;Verlet;',...
         t{7},abs(H{7}-He)+eps, '-;Gauss;');
title('Four-vortex problem, H conservation');
xlabel('t');
ylabel('H');
figure;
semilogy(t{1},abs(L{1}-Le)+eps, '-;Euler;', ...
         t{2},abs(L{2}-Le)+eps, '-;Backward Euler;', ...
         t{3},abs(L{3}-Le)+eps, '-;Trapesoidal rule;', ...
         t{4},abs(L{4}-Le)+eps, '-;Implicit midpoint rule;', ...
         t{5},abs(L{5}-Le)+eps, '-;Symplectic Euler;', ...
         t{6},abs(L{6}-Le)+eps, '-;Verlet;',...
         t{7},abs(L{7}-Le)+eps, '-;Gauss;');
title('Four-vortex problem, L conservation');
xlabel('t');
ylabel('L');
figure;
semilogy(t{1},abs(P{1}-Pe)+eps, '-;Euler;', ...
         t{2},abs(P{2}-Pe)+eps, '-;Backward Euler;', ...
         t{3},abs(P{3}-Pe)+eps, '-;Trapesoidal rule;', ...
         t{4},abs(P{4}-Pe)+eps, '-;Implicit midpoint rule;', ...
         t{5},abs(P{5}-Pe)+eps, '-;Symplectic Euler;', ...
         t{6},abs(P{6}-Pe)+eps, '-;Verlet;',...
         t{7},abs(P{7}-Pe)+eps, '-;Gauss;');
title('Four-vortex problem, P conservation');
xlabel('t');
ylabel('P');
figure;
semilogy(t{1},abs(Q{1}-Qe)+eps, '-;Euler;', ...
         t{2},abs(Q{2}-Qe)+eps, '-;Backward Euler;', ...
         t{3},abs(Q{3}-Qe)+eps, '-;Trapesoidal rule;', ...
         t{4},abs(Q{4}-Qe)+eps, '-;Implicit midpoint rule;', ...
         t{5},abs(Q{5}-Qe)+eps, '-;Symplectic Euler;', ...
         t{6},abs(Q{6}-Qe)+eps, '-;Verlet;',...
         t{7},abs(Q{7}-Qe)+eps, '-;Gauss;');
title('Four-vortex problem, Q conservation');
xlabel('t');
ylabel('Q');
