name: Run CI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt install libgsl-dev
      - run: autoreconf -if
      - run: ./configure -q
      - run: make -s
      - run: make -s check
